import AnimatedText from "@/components/AnimatedText";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faFile } from "@fortawesome/free-solid-svg-icons";
import { faBook } from "@fortawesome/free-solid-svg-icons";
import { faGuitar } from "@fortawesome/free-solid-svg-icons";
import { faCode } from "@fortawesome/free-solid-svg-icons";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import ProfilePic from "../../public/images/me.png";
import ig from "../../public/images/ig.png";
import tw from "../../public/images/tw.png";
import ld from "../../public/images/ld.png";
import { motion } from "framer-motion";
import { FaRegSmile } from "react-icons/fa";
import { faCircleArrowRight } from '@fortawesome/free-solid-svg-icons'


import Skills from "@/components/Skills";
import { useRouter } from "next/router";

const CustomLink = ({ href, title, className = "" }) => {
  const router = useRouter();

  return (
    <Link href={href} className={`${className} relative group`}>
      {title}
      <span
        className={`h-[1px] inlin-block bg-light absolute left-0 -bottom-0.5 group-hover:w-full transition-[width] ease duration-300 ${router.asPath === href ? "w-full" : " w-0"
          }`}
      ></span>
    </Link>
  );
};

const Home = () => {
  return (
    <>
      <Head>
        <title>Akshit Bansal</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className="flex flex-col min-h-screen bg-dark">
        <div className="flex flex-col mx-5 sm:mx-7 md:mx-16 lg:mx-32 xl:mx-20 mt-16 sm:mt-20">
          <div className="flex flex-col sm:flex-row sm:justify-between mt-10">
            <motion.div
              className="w-full sm:w-2/3 flex flex-col md:flex-row items-center justify-between rounded-3xl border border-solid border-dark bg-boxi shadow-2xl sm:p-12 p-5 hover:shadow-[0_0px_50px_#0a0909] transition duration-500 ease-in-out mr-8"
              style={{ minHeight: "320px" }}
              whileHover={{ scale: 1.05, boxShadow: "10px 10px 20px #0a0909" }}
              transition={{ duration: 0.27 }}
            >
              <div className="flex flex-row justify-center sm:justify-start mb-4 sm:mb-0">
                <Image
                  src={ProfilePic}
                  alt=""
                  className="w-[100%] h-auto hover:drop-shadow-image mb-8"
                />
              </div>

              <div className="w-full flex flex-col items-center sm:items-start sm:ml-8 md:ml-20 mt-4 sm:mt-0">
                <AnimatedText
                  text="Hey, I'm Akshit 👋"
                  className="!text-3xl sm:!text-4xl text-light font-semibold text-center sm:text-left"
                />

                <p className="text-sm sm:text-base font-semimedium mt-1 text-light text-center sm:text-left">
                  Bringing ideas to life through the process of Designing,
                  Creation and Development is not just a hobby, it's my passion.
                </p>
              </div>
            </motion.div>

            <motion.div
              className="w-full sm:w-1/3 mx-auto mt-7 sm:mt-0 hover:shadow-[0_0px_50px_#0a0909] flex flex-col items-center sm:items-start justify-start rounded-3xl pt-9 pr-9 pl-9 pb-4 bg-boxi transition duration-500 ease-in-out"
              whileHover={{ scale: 1.05, boxShadow: "10px 10px 20px #0a0909" }}
              transition={{ duration: 0.27 }}
              style={{ minHeight: "320px" }}
            >
              <div className="w-full flex flex-col items-center sm:items-start mt-7">
                <p className="text-5xl font-medium text-myYellow mt-16 mb-4">
                  <FontAwesomeIcon icon={faFile} />
                </p>

                <div className="text-xs sm:text-base sm:font-base mb-2 mt-1 text-light">
                  <p>More about me</p>
                </div>
                <div className="flex flex-row">
                  <CustomLink
                    href="/resume"
                    title="See my resume"
                    className="font-medium hover:text-myYellow text-white bg-transparent text-2xl  mb-4"
                  />
                  <Link href='/resume'><FontAwesomeIcon icon={faCircleArrowRight} className='text-light hover:text-myYellow text-2xl ml-5 mt-2 cursor-pointer' /></Link>
                </div>
                
              </div>
            </motion.div>
          </div>

          <div className="flex flex-col sm:flex-row sm:justify-between mt-8">
            <motion.div
              className="w-full sm:w-1/3 mx-auto mt-7 sm:mt-0 hover:shadow-[0_0px_50px_#0a0909] flex flex-col items-center sm:items-start justify-start rounded-3xl pt-9 pr-9 pl-9 pb-4 bg-boxi transition duration-500 ease-in-out mr-8"
              whileHover={{ scale: 1.05, boxShadow: "10px 10px 20px #0a0909" }}
              transition={{ duration: 0.27 }}
              style={{ minHeight: "320px" }}
            >
              <div className="w-full flex flex-col items-center sm:items-start">
                <p className="text-5xl font-medium text-myYellow mt-16 mb-4">
                  <FaRegSmile className="mr-2 text-myYellow text-5xl " />
                </p>

                <div className="text-xs sm:text-xl sm:font-semimedium mb-2 mt-1 text-light">
                  <p> Click me up, if you'r interested in working together. </p>
                </div>
                <a href="mailto:akshitmoga1@gmail.com">
                  <button className="font-medium m hover:text-myYellow hover:border-myYellow text-white bg-transparent text-xs py-2 px-4 border-2 rounded-full mt-5 ">
                    Contact Me
                  </button>
                </a>
              </div>
            </motion.div>

            <motion.div
              className="w-full sm:w-2/3 mx-auto mt-7 sm:mt-0 hover:shadow-[0_0px_50px_#0a0909] flex flex-col items-center sm:items-start justify-start rounded-3xl pt-9 pr-9 pl-9 pb-4 bg-boxi transition duration-500 ease-in-out"
              whileHover={{ scale: 1.05, boxShadow: "10px 10px 20px #0a0909" }}
              transition={{ duration: 0.27 }}
              style={{ minHeight: "320px" }}
            >
              <div className="w-full flex flex-col items-center sm:items-start">
                <p className="text-xl font-medium text-light mb-1 md:mt-20">
                  What I enjoy most.
                </p>

                <div className="flex md:flex-row flex-col xl:gap-32">
                  <div className="text-xs sm:text-xl sm:font-semimedium mb-5 mt-1 text-myYellow">
                    <p className="md:text-7xl text-5xl mb-3 md:gap-5 mt-4 text-myYellow">
                      <FontAwesomeIcon icon={faBook} />
                    </p>
                    <p className="hidden md:block text-center text-lg text-light">
                      Reading
                    </p>
                  </div>
                  <div className="text-xs sm:text-xl sm:font-semimedium mb-5 mt-1 text-myYellow">
                    <p className="md:text-7xl text-5xl mb-3 md:gap-5 mt-4 text-myYellow">
                      <FontAwesomeIcon icon={faGuitar} />
                    </p>
                    <p className="hidden md:block text-center text-lg text-light ">
                      Guitar
                    </p>
                  </div>
                  <div className="text-xs sm:text-xl sm:font-semimedium mb-5 mt-1 text-myYellow">
                    <p className="md:text-7xl text-5xl mb-3 md:gap-5 mt-4 text-myYellow">
                      <FontAwesomeIcon icon={faCode} />
                    </p>
                    <p className="hidden md:block text-center text-lg text-light">
                      Coding
                    </p>
                  </div>
                </div>
              </div>
            </motion.div>
          </div>

          <div className="flex flex-col sm:flex-row sm:justify-between mt-8">
            <motion.div
              className="w-full sm:w-1/3 flex flex-col items-center justify-center rounded-3xl border border-solid border-dark bg-boxi shadow-2xl p-5 pr- hover:shadow-[0_0px_50px_#0a0909] transition duration-500 ease-in-out mr-8"
              style={{ minHeight: "320px" }}
              whileHover={{ scale: 1.05, boxShadow: "10px 10px 20px #0a0909" }}
              transition={{ duration: 0.27 }}
            >
              <a
                href="https://www.linkedin.com/in/akshit-bansal-404952227/"
                target="_blank"
                className="flex items-center justify-center h-full w-full"
              >
                <Image src={ld} alt="" className="h-28 w-32 sm:w-40 sm:h-36" />
              </a>
              <div className="w-full flex flex-col items-center mt-4">
                <p className="text-lg font-medium mb-5 sm:mt-1 text-light text-center">
                  Let's expand our networks
                </p>
              </div>
            </motion.div>
            <motion.div
              className="w-full sm:w-1/3 flex flex-col mt-5 sm:mt-0 items-center justify-center rounded-3xl border border-solid border-dark bg-boxi shadow-2xl p-5 hover:shadow-[0_0px_50px_#0a0909] transition duration-500 ease-in-out mr-8"
              style={{ minHeight: "320px" }}
              whileHover={{ scale: 1.05, boxShadow: "10px 10px 20px #0a0909" }}
              transition={{ duration: 0.27 }}
            >
              <a
                href="https://www.instagram.com/desii.thoughts/"
                target="_blank"
                className="flex items-center justify-center h-full w-full"
              >
                <Image src={ig} alt="" className="h-28 w-32 sm:w-40 sm:h-36" />
              </a>
              <div className="w-full flex flex-col items-center mt-4">
                <p className="text-lg font-medium mb-5 mt-1 text-light text-center">
                  Discover more about me
                </p>
              </div>
            </motion.div>
            <motion.div
              className="w-full sm:w-1/3 flex mt-5 sm:mt-0 flex-col items-center justify-center rounded-3xl border border-solid border-dark bg-boxi shadow-2xl p-5 hover:shadow-[0_0px_50px_#0a0909] transition duration-500 ease-in-out "
              style={{ minHeight: "320px" }}
              whileHover={{ scale: 1.05, boxShadow: "10px 10px 20px #0a0909" }}
              transition={{ duration: 0.27 }}
            >
              <a
                href="https://twitter.com/akshiitbansal"
                target="_blank"
                className="flex items-center justify-center h-full w-full"
              >
                <Image src={tw} alt="" className="h-28 w-32 sm:w-40 sm:h-36" />
              </a>
              <div className="w-full flex flex-col items-center mt-4">
                <p className="text-lg font-medium mb-5 mt-1 text-light text-center">
                  Stay up-to-date with me
                </p>
              </div>
            </motion.div>
          </div>
         
        </div>
      </main>
    </>
  );
};

export default Home;
